paths:
  raw_data: /Volumes/SSD/Epfl/Master/MA3/FBD/data/raw/
  intermediate_data: /Volumes/SSD/Epfl/Master/MA3/FBD/data/intermediate/
  processed_data: /Volumes/SSD/Epfl/Master/MA3/FBD/data/processed/
  results_data: /Volumes/SSD/Epfl/Master/MA3/FBD/data/results/
  visualisations: /Volumes/SSD/Epfl/Master/MA3/FBD/reports/figures/
  masks: /Volumes/SSD/Epfl/Master/MA3/FBD/data/masks/

paths_local:
  raw_data: data/raw/
  intermediate_data: data/intermediate/
  processed_data: data/processed/
  results_data: data/results/
  visualisations: reports/figures/
  masks: data/masks/

rolling_calibrations:
  start_date: 2005-04-24 22:00:00
  end_date: 2024-12-31 23:00:00
  window_size: 1825 # in days
  step_size: 365 # in days
  gap_size: 30 # in days
  eval_size: 365 # in days
  final_window_size: 5110 # in days
  final_eval_size: 1460 # in days

mean_variance_optimization:
  total_turbines: 100
  lambda_values:
    [0.0, 0.00005, 0.00001, 0.0001, 0.0005, 0.001, 0.01, 1.0, "random"]
  min_revenue_threshold: 0.0

clustering:
  n_workers: 4
  threads_per_worker: 1
  memory_limit: 4GB
