data_source:
  weather:
    hourly:
      url: https://thredds-su.ipsl.fr/thredds/catalog/aeris_thredds/actrisfr_data/665029c8-82b8-4754-9ff4-d558e640b0ba/catalog.html

paths:
  raw_data: /data/raw/
  processed_data: /data/processed/
