paths:
  raw_data: /Volumes/SSD/Epfl/Master/MA3/FBD/data/raw/
  intermediate_data: /Volumes/SSD/Epfl/Master/MA3/FBD/data/intermediate/
  processed_data: /Volumes/SSD/Epfl/Master/MA3/FBD/data/processed/
  visualisations: /Volumes/SSD/Epfl/Master/MA3/FBD/reports/figures/


paths_local:
  raw_data: data/raw/
  intermediate_data: data/intermediate/
  processed_data: data/processed/
  visualisations: reports/figures/
